[server]
headless = true
address = "localhost"
port = 5000

[theme]
# Light mode settings (default)
primaryColor = "#4CAF50"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

# Uncomment these for dark mode
# primaryColor = "#4CAF50"
# backgroundColor = "#0E1117"
# secondaryBackgroundColor = "#1E2530"
# textColor = "#FAFAFA"